# Use the official PostgreSQL image as the base image
FROM postgres:13

# Set environment variables
ENV POSTGRES_DB=python-challenge
ENV POSTGRES_USER=matiasmacadden
ENV POSTGRES_PASSWORD=1234

# Expose PostgreSQL default port
EXPOSE 5432